"""create users table

Revision ID: 510ef145a0cd
Revises: e0a79e155c38
Create Date: 2025-07-15 12:28:43.243925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510ef145a0cd'
down_revision: Union[str, Sequence[str], None] = 'e0a79e155c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('usermodel', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.drop_column('usermodel', 'lastName')
    op.drop_column('usermodel', 'firstName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('firstName', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('usermodel', sa.Column('lastName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('usermodel', 'last_name')
    op.drop_column('usermodel', 'first_name')
    # ### end Alembic commands ###
